name: porefile
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bc
  - wget
  - procps-ng
  - porechop
  - nanofilt
  - nanoplot
  - seqkit
  - minimap2
  - r-base
  - r-optparse
  - r-magrittr
  - r-dplyr
  - yacrd
  - samtools
  - megan
