name: porefile
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - wget
  - procps-ng
  - openjdk
  - porechop
  - nanofilt
  - nanoplot
  - seqtk
  - last
  - minimap2
  - r-base
  - blast
  - samtools
  - yacrd
