name: porefile
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - wget=1.20.1
  - procps-ng=3.3.16
  - openjdk=11.0.8
  - porechop=0.2.4
  - nanofilt=2.7.1
  - nanoplot
  - seqtk=1.3-r106
  - last=1060
  - minimap2=2.17-r941
  - r-base=4.0.3
  - blast=2.10.1
  - yacrd=0.6.2
