name: porefile
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bc=1.07.1
  - wget=1.20.1
  - procps-ng
  - openjdk=11.0.9.1
  - porechop=0.2.4
  - nanofilt=2.8.0
  - nanoplot=1.38.0
  - seqtk=1.3
  - last=1238
  - minimap2=2.21
  - r-base=4.1.0
  - blast=2.11.0
  - yacrd=0.6.2
